data:
  train_path: ../data/raw/train.csv
  test_path: ../data/raw/test.csv
  processed_dir: ../data/processed

output:
  model_dir: "../outputs/models"           # Where to save trained models
  figures_dir: "../outputs/figures"        # Where to save charts/plots
  predictions_dir: "../outputs/predictions" # Where to save prediction CSVs

test_size: 0.2          # Train/test split fraction
random_seed: 42         # Random seed for reproducibility

model:
  target_column: "target"    # target variable name
