xgboost:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

random_forest:
  n_estimators: 300
  max_depth: 10
  min_samples_split: 2
  random_state: 42